### PR TITLE
Revert "Add files via upload"

### PR DESCRIPTION
**Pull request by BAFR-GregoryM**
Reverts formationGitMFC/cree_ton_aventure#13

### CODE REVIEW

**Comment by BAFR-JonathanP** [comment]
Hors de question !!

**Comment by BAFR-JonathanP** [comment]
Vote BAN

**Comment by BAFR-GregoryM** [comment]
BAN de Jonathan

**Comment by BAFR-GregoryM** [comment]
image

**Comment by BAFR-JonathanP** [comment]
Greg le noob !

**Comment by BAFR-GregoryM** [comment]
Tu crois encore au 
image

**Pull request closed without merging**
